import type {
  Activity,
  SavedTripSummary,
  Trip,
  TripRequest,
} from "@/types/trip";

/**
 * UI preview data only. Shaped like future /api/travel-plan responses.
 * Not live travel, weather, or booking data.
 */
const PREVIEW_NOTICE =
  "Preview itinerary for UI demonstration. Not generated by the Steora planning engine.";

function activity(
  partial: Omit<Activity, "costIsEstimate"> & { costIsEstimate?: boolean },
): Activity {
  return { ...partial, costIsEstimate: partial.costIsEstimate ?? true };
}

const defaultRequest: TripRequest = {
  destination: {
    query: "Kyoto",
    name: "Kyoto",
    country: "Japan",
    placeId: "sample:kyoto",
    coordinates: { lat: 35.0116, lng: 135.7681 },
    resolution: "resolved",
  },
  startDate: "2026-04-10",
  endDate: "2026-04-13",
  travelers: 2,
  budget: 3200,
  currency: "USD",
  interests: ["culture", "food", "history", "photography"],
  travelStyle: "balanced",
  dailyPace: "moderate",
  maxTravelTimeMinutes: 30,
  additionalPreferences: "Prefer walkable neighborhoods and quieter evenings.",
};

export const PREVIEW_SAVED_TRIPS: SavedTripSummary[] = [
  {
    id: "preview-kyoto",
    destinationName: "Kyoto, Japan",
    startDate: "2026-04-10",
    endDate: "2026-04-13",
    travelers: 2,
    budget: 3200,
    currency: "USD",
    travelStyle: "balanced",
    updatedAt: "2026-03-02T10:00:00.000Z",
    status: "valid",
  },
  {
    id: "preview-lisbon",
    destinationName: "Lisbon, Portugal",
    startDate: "2026-06-04",
    endDate: "2026-06-08",
    travelers: 1,
    budget: 1800,
    currency: "EUR",
    travelStyle: "budget",
    updatedAt: "2026-02-18T16:20:00.000Z",
    status: "warning",
  },
];

const PREVIEW_REQUESTS: Record<string, TripRequest> = {
  "preview-kyoto": defaultRequest,
  "preview-lisbon": {
    destination: {
      query: "Lisbon",
      name: "Lisbon",
      country: "Portugal",
      placeId: "sample:lisbon",
      coordinates: { lat: 38.7223, lng: -9.1393 },
      resolution: "resolved",
    },
    startDate: "2026-06-04",
    endDate: "2026-06-08",
    travelers: 1,
    budget: 1800,
    currency: "EUR",
    interests: ["food", "history", "culture"],
    travelStyle: "budget",
    dailyPace: "moderate",
    maxTravelTimeMinutes: 25,
    additionalPreferences: "Prefer public transit over taxis.",
  },
};

export function buildPreviewTrip(id: string, request?: TripRequest): Trip {
  const resolvedRequest = request ?? PREVIEW_REQUESTS[id] ?? defaultRequest;
  const start = resolvedRequest.startDate || defaultRequest.startDate;
  const day2 = shiftDate(start, 1);
  const day3 = shiftDate(start, 2);

  return {
    id,
    status: id === "preview-lisbon" ? "warning" : "valid",
    createdAt: "2026-03-01T09:00:00.000Z",
    updatedAt: "2026-03-02T10:00:00.000Z",
    request: resolvedRequest,
    weather: [
      {
        date: start,
        condition: "Clear",
        summary: "Mild and dry — preview weather, not a live forecast.",
        highC: 18,
        lowC: 9,
        precipitationChance: 10,
      },
      {
        date: day2,
        condition: "Partly cloudy",
        summary: "Light cloud cover in the afternoon.",
        highC: 17,
        lowC: 8,
        precipitationChance: 20,
      },
      {
        date: day3,
        condition: "Showers",
        summary: "Brief showers possible late day.",
        highC: 16,
        lowC: 8,
        precipitationChance: 45,
      },
    ],
    feasibility: {
      overall: "valid",
      checks: [
        {
          id: "budget",
          label: "Budget feasibility",
          status: "valid",
          summary: "Estimated spend sits inside the stated budget.",
        },
        {
          id: "schedule",
          label: "Schedule feasibility",
          status: "valid",
          summary: "Day blocks fit the selected pace without overlap.",
        },
        {
          id: "travel_time",
          label: "Travel-time feasibility",
          status: "warning",
          summary:
            "One afternoon transfer is close to the maximum preferred travel time.",
        },
        {
          id: "distance",
          label: "Distance feasibility",
          status: "valid",
          summary: "Activities are clustered by neighborhood.",
        },
        {
          id: "weather",
          label: "Weather suitability",
          status: "valid",
          summary: "Outdoor stops are placed on drier preview days.",
        },
      ],
    },
    budgetBreakdown: {
      currency: resolvedRequest.currency,
      totalBudget: resolvedRequest.budget,
      estimatedTotal: Math.min(
        resolvedRequest.budget,
        Math.round(resolvedRequest.budget * 0.86),
      ),
      bookedTotal: null,
      lines: [
        {
          category: "activities",
          estimated: Math.round(resolvedRequest.budget * 0.22),
          booked: null,
        },
        {
          category: "food",
          estimated: Math.round(resolvedRequest.budget * 0.2),
          booked: null,
        },
        {
          category: "local_transport",
          estimated: Math.round(resolvedRequest.budget * 0.08),
          booked: null,
        },
        {
          category: "accommodation",
          estimated: Math.round(resolvedRequest.budget * 0.32),
          booked: null,
        },
        {
          category: "other",
          estimated: Math.round(resolvedRequest.budget * 0.04),
          booked: null,
        },
      ],
    },
    itinerary: {
      days: [
        {
          dayNumber: 1,
          date: start,
          weather: {
            date: start,
            condition: "Clear",
            summary: PREVIEW_NOTICE,
            highC: 18,
            lowC: 9,
            precipitationChance: 10,
          },
          segments: {
            morning: [
              activity({
                id: "d1-m1",
                name: "Neighborhood orientation walk",
                category: "activity",
                locationName: "Historic core",
                coordinates: { lat: 35.0116, lng: 135.7681 },
                startTime: "09:00",
                durationMinutes: 90,
                estimatedCost: 0,
                costIsEstimate: true,
                reasons: [
                  {
                    code: "matches_travel_style",
                    label: "Matches travel style",
                    detail: "A lighter start matches a balanced pace.",
                  },
                  {
                    code: "fits_available_time",
                    label: "Fits available time",
                    detail: "Leaves buffer before the first indoor stop.",
                  },
                ],
                source: { name: "Preview dataset" },
              }),
            ],
            afternoon: [
              activity({
                id: "d1-a1",
                name: "Temple and garden circuit",
                category: "culture",
                locationName: "Eastern hills",
                coordinates: { lat: 35.002, lng: 135.785 },
                startTime: "13:00",
                durationMinutes: 150,
                estimatedCost: 18,
                costIsEstimate: true,
                distanceFromPreviousKm: 3.4,
                travelTimeFromPreviousMinutes: 22,
                reasons: [
                  {
                    code: "matches_interests",
                    label: "Matches selected interests",
                    detail: "Aligns with culture, history, and photography.",
                  },
                  {
                    code: "suitable_for_weather",
                    label: "Suitable for weather",
                    detail: "Outdoor gardens sit on the clearest preview day.",
                  },
                ],
                source: { name: "Preview dataset" },
              }),
            ],
            evening: [
              activity({
                id: "d1-e1",
                name: "Market supper",
                category: "food",
                locationName: "Central market street",
                startTime: "18:30",
                durationMinutes: 90,
                estimatedCost: 42,
                costIsEstimate: true,
                distanceFromPreviousKm: 2.1,
                travelTimeFromPreviousMinutes: 18,
                reasons: [
                  {
                    code: "fits_budget",
                    label: "Fits budget",
                    detail: "Estimated meal cost stays inside the food allocation.",
                  },
                  {
                    code: "close_to_previous",
                    label: "Close to previous activity",
                    detail: "Keeps evening travel under the preferred maximum.",
                  },
                ],
                source: { name: "Preview dataset" },
              }),
            ],
          },
        },
        {
          dayNumber: 2,
          date: day2,
          weather: {
            date: day2,
            condition: "Partly cloudy",
            summary: PREVIEW_NOTICE,
            highC: 17,
            lowC: 8,
            precipitationChance: 20,
          },
          segments: {
            morning: [
              activity({
                id: "d2-m1",
                name: "Craft neighborhood studios",
                category: "culture",
                locationName: "Artisan district",
                startTime: "09:30",
                durationMinutes: 120,
                estimatedCost: 28,
                costIsEstimate: true,
                reasons: [
                  {
                    code: "matches_interests",
                    label: "Matches selected interests",
                    detail: "Supports culture and photography without a packed morning.",
                  },
                ],
                source: { name: "Preview dataset" },
              }),
            ],
            afternoon: [
              activity({
                id: "d2-a1",
                name: "River path and viewpoint",
                category: "nature",
                locationName: "River corridor",
                startTime: "13:30",
                durationMinutes: 100,
                estimatedCost: 0,
                costIsEstimate: true,
                distanceFromPreviousKm: 4.8,
                travelTimeFromPreviousMinutes: 28,
                reasons: [
                  {
                    code: "matches_interests",
                    label: "Matches selected interests",
                    detail: "Adds a nature stop without exceeding travel-time preference.",
                  },
                  {
                    code: "fits_available_time",
                    label: "Fits available time",
                    detail: "Leaves recovery time before dinner.",
                  },
                ],
                source: { name: "Preview dataset" },
              }),
            ],
            evening: [
              activity({
                id: "d2-e1",
                name: "Reservation-free neighborhood dinner",
                category: "food",
                locationName: "Residential lane",
                startTime: "19:00",
                durationMinutes: 100,
                estimatedCost: 55,
                costIsEstimate: true,
                distanceFromPreviousKm: 1.6,
                travelTimeFromPreviousMinutes: 12,
                reasons: [
                  {
                    code: "matches_travel_style",
                    label: "Matches travel style",
                    detail: "Keeps the evening unhurried.",
                  },
                  {
                    code: "fits_budget",
                    label: "Fits budget",
                    detail: "Estimated, not a booked restaurant price.",
                  },
                ],
                source: { name: "Preview dataset" },
              }),
            ],
          },
        },
        {
          dayNumber: 3,
          date: day3,
          weather: {
            date: day3,
            condition: "Showers",
            summary: PREVIEW_NOTICE,
            highC: 16,
            lowC: 8,
            precipitationChance: 45,
          },
          segments: {
            morning: [
              activity({
                id: "d3-m1",
                name: "Indoor museum block",
                category: "culture",
                locationName: "Museum quarter",
                startTime: "10:00",
                durationMinutes: 140,
                estimatedCost: 16,
                costIsEstimate: true,
                reasons: [
                  {
                    code: "suitable_for_weather",
                    label: "Suitable for weather",
                    detail: "Indoor morning on the wettest preview day.",
                  },
                  {
                    code: "fits_budget",
                    label: "Fits budget",
                    detail: "Low estimated admission cost.",
                  },
                ],
                source: { name: "Preview dataset" },
              }),
            ],
            afternoon: [
              activity({
                id: "d3-a1",
                name: "Covered market tasting",
                category: "food",
                locationName: "Covered market",
                startTime: "13:30",
                durationMinutes: 80,
                estimatedCost: 24,
                costIsEstimate: true,
                distanceFromPreviousKm: 1.1,
                travelTimeFromPreviousMinutes: 10,
                reasons: [
                  {
                    code: "close_to_previous",
                    label: "Close to previous activity",
                    detail: "Short transfer after the museum block.",
                  },
                  {
                    code: "matches_interests",
                    label: "Matches selected interests",
                    detail: "Food-focused without adding long travel.",
                  },
                ],
                source: { name: "Preview dataset" },
              }),
            ],
            evening: [
              activity({
                id: "d3-e1",
                name: "Slow return and packing buffer",
                category: "rest",
                locationName: "Stay area",
                startTime: "17:30",
                durationMinutes: 90,
                estimatedCost: 0,
                costIsEstimate: true,
                distanceFromPreviousKm: 2.4,
                travelTimeFromPreviousMinutes: 16,
                reasons: [
                  {
                    code: "matches_travel_style",
                    label: "Matches travel style",
                    detail: "Protects the last evening from over-scheduling.",
                  },
                  {
                    code: "fits_available_time",
                    label: "Fits available time",
                    detail: "Leaves slack if showers persist.",
                  },
                ],
                source: { name: "Preview dataset" },
              }),
            ],
          },
        },
      ],
    },
  };
}

function shiftDate(isoDate: string, days: number) {
  const date = new Date(`${isoDate}T00:00:00`);
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}
